language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  - docker build -t udagram-api-feed ./udagram-api-feed # building docker images
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed jolinlie/udagram-api-feed # tagging
  - docker tag udagram-api-user jolinlie/udagram-api-user
  - docker tag udagram-frontend jolinlie/udagram-frontend
  - docker tag udagram-reverseproxy jolinlie/udagram-reverseproxy

after_success:
  - echo DOCKER_PASSWORD | docker login -u DOCKER_USERNAME --password-stdin
  - docker push jolinlie/udagram-api-feed
  - docker push jolinlie/udagram-api-user
  - docker push jolinlie/udagram-frontend
  - docker push jolinlie/udagram-reverseproxy